routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('home');
// });
// Route::get('/', 'HomeController@home')->name('home')->middleware('auth');
Route::get('/', 'HomeController@home')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/secret', 'HomeController@secret')->name('secret')->middleware('can:home.secret');
Route::get('/author', 'HomeController@authorDetails')->name('author-details');
Route::resource('posts', 'PostController');
Route::get('/posts/tag/{tag}','PostTagController@index')->name('posts.tags.index');
Route::resource('posts.comments', 'PostCommentController')->only(['store']);
Route::resource('users.comments', 'UserCommentController')->only(['store']);
Route::resource('users', 'UserController')->only(['show','edit','update']);
Auth::routes();

app/User.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function blogPosts(){
        return $this->hasMany('App\BlogPost');
    }
    /**
     * Get all  user's comments.
     */
    public function comments(){
        return $this->hasMany('App\Comment');
    }
     /**
     * Get all of the  comments on user.
     */
    public function commentsOn()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
     /**
     * Get the user's image.
     */
    public function image()
    {
        return $this->morphOne('App\Image', 'imageable');
    }

    public function scopeWithMostBlogPosts(Builder $query)
    {
       return $query->withCount('blogPosts')->orderBy('blog_posts_count','desc');
    }

    public function scopeWithMostBlogPostsLastMonth(Builder $query)
    {
        return $query->withCount(['blogPosts'=>function(Builder $query){
        $query->whereBetween(static::CREATED_AT,[now()->subMonths(1),now()]);
        }])->has('blogPosts','>=',2)->orderBy('blog_posts_count','desc');

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Image;
use Illuminate\Http\Request;
use App\Http\Requests\UpdateUser;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function __construct()
    {
       $this->middleware('auth');
       $this->authorizeResource('User::class','user');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show',['user'=> $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit',['user'=> $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUser $request, User $user)
    {
       if($request->hasFile('avatar'))
       {
          $paths = $request->file('avatar');
          $path =  $paths->storeAs('UserimageThumbnail', $user->id.'.'.$paths->guessExtension());
          if($user->image){
            Storage::delete($user->image->path);
            $user->image->path = $path;
            $user->image->save();
        }else{
            $user->image()->save(
              Image::make(['path'=>$path])
           );
        }
        return redirect()->back()->withStatus('profile image was created!!');
       }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/edit.blade.php
@extends('layouts.front')

@section('content')
    <form method="POST" enctype="multipart/form-data" action="{{ route('users.update',['user'=> $user->id]) }}"
        class="form-horizontal">
        @csrf
        @method('put')
            <div class="row">
            <div class="col-4">
                @if ($user->image)
                <img src="{{ asset('http://127.0.0.1:8000/storage/'.'/'.$user->image->path) }}"  class="img-thumbnail avatar"/> 
                @endif  
                <div class="card mt-4">
                    <div class="card-body">
                        <h6>Upload a different photo</h6>
                        <input type="file" name="avatar" id="" class="form-control-file">
                    </div>
                </div>
                @error
               @enderror
            </div>
            <div class="col-8">
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" name="name" id="" class="form-control" value="">
                </div>
                <div class="form-group">
                    <input type="submit" value="save changes!" class="btn btn-primary">
                </div>
            </div>
            </div>
    </form>
@endsection

resources/views/users/show.blade.php
@extends('layouts.front')

@section('content')
    <div class="row">
    <div class="col-4">
        @if ($user->image)
        <img src="{{ asset('http://127.0.0.1:8000/storage/'.'/'.$user->image->path) }}"  class="img-thumbnail avatar"/> 
        @endif  
    </div>
    <div class="col-8">
        <h3>{{ $user->name }}</h3>
        @commentForm(['route'=> route('users.comments.store',['user'=>$user->id])])
        @endcommentForm
        @commentList(['comments'=>$user->commentsOn])
        @endcommentList
        <a href="{{ route('users.edit',['user'=>$user])}}" class="btn btn-primary">Edit Profile</a>
    </div>
   
    </div>
@endsection