routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('home');
// });
// Route::get('/', 'HomeController@home')->name('home')->middleware('auth');
Route::get('/', 'HomeController@home')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/secret', 'HomeController@secret')->name('secret')->middleware('can:home.secret');
Route::get('/author', 'HomeController@authorDetails')->name('author-details');
Route::resource('posts', 'PostController');
Route::get('/posts/tag/{tag}','PostTagController@index')->name('posts.tags.index');
Route::resource('posts.comments', 'PostCommentController')->only(['store']);
Route::resource('users.comments', 'UserCommentController')->only(['store']);
Route::resource('users', 'UserController')->only(['show','edit','update']);
Auth::routes();

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Image;
use App\BlogPost;
use App\Comment;
use Illuminate\Http\Request;
use App\Http\Requests\StorePost;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->only(['create','store','edit','update','destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //DB::connection()->enableQueryLog();
       // $posts = BlogPost::all();
        // $posts = BlogPost::with('comments')->get();
        // foreach($posts as $post){
        //     foreach($post->comments as $comment){
        //        echo $comment->content;
        //     }
        // }
        //dd(DB::getQueryLog());
        return view('posts.index',
        ['posts'=> BlogPost::withCount('comments')->with('tags')->orderBy('created_at', 'desc')->get(),
        'mostCommented'=>BlogPost::mostCommented()->take(5)->get(),
        'mostActive' =>User::withMostBlogPosts()->take(3)->get(),
        'mostActiveLastMonth' =>User::withMostBlogPostsLastMonth()->take(3)->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $this->authorize('posts.create');
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePost $request)
    {
        $validatedata = $request->validated();
        $validatedata['user_id'] = $request->user()->id;
       // dd($request->all());
       $blogpost = BlogPost::create($validatedata);
       //file store
       $hasFile = $request->hasFile('thumbnail');

       if($hasFile)
       {
          $paths = $request->file('thumbnail');
          $path =  $paths->storeAs('imageThumbnail', $blogpost->id.'.'.$paths->guessExtension());

          $blogpost->image()->save(
             Image::make(['path'=>$path])
          );
        //   dump($path);
        //   dump($path->getClientMimeType());
        //   dump($path->getClientOriginalExtension());
        // //   $path->store('imageThumbnail');
        //   $url = $path->storeAs('imageThumbnail',$blogpost->id.'.'.$file->guessExtensioncreate());
        //   dump(Storage::url($url));
       }
       
    
    //    $blogpost = new BlogPost();
    //    $blogpost->title = $request->input('title');
    //    $blogpost->content = $request->input('content');
    //    $blogpost->save();
       $request->session()->flash('status','Blog post was created!');
       return redirect()->route('posts.show',['post'=>$blogpost->id]);
    }

    // /**
    //  * Display the specified resource.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function show($id)
    {
        return view('posts.show',
        ['post'=>BlogPost::with(['comments'=>function($query){
          return $query->latest();
        }])->with('tags')->with('user')->findOrFail($id),
        'mostCommented'=>BlogPost::mostCommented()->take(5)->get(),
        'mostActive' =>User::withMostBlogPosts()->take(3)->get(),
        'mostActiveLastMonth' =>User::withMostBlogPostsLastMonth()->take(3)->get()
        ]);
        //dd(BlogPost::find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Blogpost::findorFail($id);
        return view('posts.edit',['post'=>$post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorePost $request, $id)
    {
        $post = Blogpost::findorFail($id);
        //same work as gate 
        //$this->authorize('posts.update',$post);
        $this->authorize('update',$post);
        // if(Gate::denies('update-post',$post)){
        //     abort(403,"You can't edit this blog post");
        // }
        $validatedata = $request->validated();
        $post->fill($validatedata);

        $hasFile = $request->hasFile('thumbnail');

       if($hasFile)
       {
          $paths = $request->file('thumbnail');
          $path =  $paths->storeAs('imageThumbnail', $post->id.'.'.$paths->guessExtension());
          if($post->image){
              Storage::delete($post->image->path);
              $post->image->path = $path;
              $post->image->save();
          }else{
             $post->image()->save(
                Image::make(['path'=>$path])
             );
          }
        } 
        $post->save();
        $request->session()->flash('status','Blog post was updated!');
        return redirect()->route('posts.show',['post'=>$post->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        // BlogPost::destroy($id);
        $post = BlogPost::findorFail($id);
        // $result2 = Comment::where('blog_post_id', $id)->delete();
        // $result3 = Image::where('blog_post_id', $id)->delete();
        $this->authorize('delete',$post);
        // if(Gate::denies('delete-post',$post)){
        //     abort(403,"You can't delete this blog post");
        // }
        $post->delete();
        $request->session()->flash('status','Post was deleted successfully!');
        return redirect()->route('posts.index');
    }
}

resources/views/posts/_activity.blade.php
<div class="container">
    <div class="row">
       <div class="card" style="width: 100%;">
       <div class="card-body">
       <h5 class="card-title">Most Commented</h5>
        <h6 class="card-subtitle mb-2 text-muted">What people are currently talking about.</h6>
        </div>
        <ul class="list-group list-group-flush"> 
        @foreach ( $mostCommented as $post)
        <a href="{{route('posts.show',['post'=>$post->id])}}">
        <li class="list-group-item">{{ $post->title }}</li>
        </a>
        @endforeach
        </ul>
      </div>
   </div>

   <div class="row mt-4">
    <div class="card" style="width: 100%;">
    <div class="card-body">
    <h5 class="card-title">Most Active Users</h5>
     <h6 class="card-subtitle mb-2 text-muted">Users with most posts written</h6>
     </div>
     <ul class="list-group list-group-flush"> 
     @foreach ( $mostActive as $user)
     <li class="list-group-item">{{ $user->name }}</li>
     @endforeach
     </ul>
   </div>
</div>

<div class="row mt-4">
    <div class="card" style="width: 100%;">
    <div class="card-body">
    <h5 class="card-title">Most Active Users in last month</h5>
     <h6 class="card-subtitle mb-2 text-muted">Users with most posts written in last month</h6>
     </div>
     <ul class="list-group list-group-flush"> 
     @foreach ( $mostActiveLastMonth as $user)
     <li class="list-group-item">{{ $user->name }}</li>
     @endforeach
     </ul>
   </div>
</div>
</div>

resources/views/posts/_form.blade.php
<div class="form-group">
    <label>Title</label>
    <input type="text" class="form-control" name="title" value="{{old('title',$post->title ?? null)}}">
</div>
<div class="form-group">
    <label>Content</label>
    <input type="text" class="form-control" name="content" value="{{ old('content',$post->content ?? null)}}">
</div>
<div class="form-group">
    <label for="thumbnail">Thumbnail</label>
    <input type="file" name="thumbnail" id="" class="form-control-file" 
    value="{{ old('thumbnail') }}">
</div>
@error
@enderror

resources/views/posts/create.blade.php
@extends('layouts.front')
@section('content')
<form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
   @include('posts._form')
    <button type="submit" class="btn btn-primary btn-block">Create</button>
</form>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.front')
@section('content')
<form action="{{route('posts.update',['post'=>$post->id])}}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    @include('posts._form')
    <button type="submit" class="btn btn-primary btn-block">Update</button>
</form>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.front')
@section('content')
<div class="row">
    <div class="col-8">
@forelse ($posts as $post)
    <p>
    <h3><a href="{{route('posts.show',['post'=>$post->id])}}">{{$post->title}}</a></h3>
    {{-- <p class="text-muted">
        Added {{ $post->created_at->diffForHumans() }}
        by {{ $post->user->name }}
    </p> --}}
    @component('components.updated',['date'=>$post->created_at,'name'=>$post->user->name,'userId'=>$post->user->id])
        {{-- blank slot --}}
    @endcomponent
    @component('components.tags',['tags'=>$post->tags])
        {{-- blank slot --}}
    @endcomponent
    @if($post->comments_count)
        <p>{{$post->comments_count}} Comments</p>
        @else
        <p>No comments yet!!</p>
    @endif
    @can('update',$post)
    <a href="{{ route('posts.edit',['post'=>$post->id])}}" class="btn btn-primary">Edit Post</a>  
    @endcan
    {{-- @cannot('delete',$post)
        <p>You can not delete this post!</p>
    @endcannot --}}
    @can('delete',$post)
    <form action="{{route('posts.destroy',['post'=>$post->id])}}" method="POST" class="fm-inline">
        @csrf
        @method('DELETE')
      <input type="submit" value="Delete" class="btn btn-primary">
    </form> 
    @endcan
    </p>
    @empty
        <p>No Blog Post yet!</p>
@endforelse
</div>
<div class="col-4">
    @include('posts._activity')
</div>
</div>
@endsection
    

resources/views/posts/show.blade.php
@extends('layouts.front')
@section('content')
<div class="row">
    <div class="col-8">
        @if($post->image)
         <div style="background-image: url('{{ asset('storage'.'/'.$post->image->path) }}'); 
           min-height: 400px; color: white; text-align: center; background-attachment: fixed; width: auto;">
             <h1 style="padding-top: 100px; text-shadow: 1px 2px #000;">
        @else
           <h1>
        @endif
<h1>{{$post->title}}
@if ((new carbon\carbon())->diffInMinutes($post->created_at) < 20)
@component('components.badge')
New Post one !!
@endcomponent
@elseif ((new carbon\carbon())->diffInMinutes($post->created_at) > 20)
@component('components.badge',['type'=>'primary'])
old Post !!
@endcomponent
@else
    Something else
@endif
</h1>
@if($post->image)
           </h1>
        </div>
        @else
    </h1>
        @endif
<p>{{$post->content}}<br>
    {{-- <img src="http://127.0.0.1:8000/storage/{{ $post->image->path }}" alt="" srcset=""/> --}}
    {{-- <img src="{{ asset('storage'.'/'.$post->image->path) }}" alt="" srcset=""> --}}
    {{-- <img src=" {{Storage::url( $post->image->path) }}" alt="" srcset=""/> --}}
    {{-- <img src="{{ $post->image->url() }}" alt="" srcset=""> --}}
@component('components.updated',['date'=>$post->created_at,'name'=>$post->user->name])
    {{-- empty slot --}}
@endcomponent
@component('components.updated',['date'=>$post->updated_at,'name'=>$post->user->name])
updated
@endcomponent
</p>
@component('components.tags',['tags'=>$post->tags])
        {{-- blank slot --}}
@endcomponent
<h4>Comments</h4>
{{-- @include('comments._form') --}}
@commentForm(['route'=> route('posts.comments.store',['post'=>$post->id])])
@endcommentForm
@commentList(['comments'=>$post->comments])
@endcommentList
{{-- @forelse ($post->comments as $comment)
    <p>
        {{ $comment->content }} ,
        <p class="text-muted">
            @component('components.updated',['date'=>$comment->created_at,'name'=>$comment->user->name])
           {{-- blank slot --}}
           {{-- @endcomponent --}}
        {{-- </p>
    </p>
@empty
    <p>No Comments yet!!</p>
@endforelse --}} 
    </div>
    <div class="col-4">
        @include('posts._activity')
    </div>
@endsection