routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('home');
// });
// Route::get('/', 'HomeController@home')->name('home')->middleware('auth');
Route::get('/', 'HomeController@home')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/secret', 'HomeController@secret')->name('secret')->middleware('can:home.secret');
Route::get('/author', 'HomeController@authorDetails')->name('author-details');
Route::resource('posts', 'PostController');
Route::get('/posts/tag/{tag}','PostTagController@index')->name('posts.tags.index');
Route::resource('posts.comments', 'PostCommentController')->only(['store']);
Route::resource('users.comments', 'UserCommentController')->only(['store']);
Route::resource('users', 'UserController')->only(['show','edit','update']);
Auth::routes();

app/Comment.php
<?php

namespace App;

use App\Traits\Taggable;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use Taggable;
    protected $fillable = ['user_id','content'];
    
    public function commentable()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
     /**
     * Get all of the tags for the comment.
     */
    public function tags()
    {
        return $this->morphToMany('App\Tag', 'taggable')->withTimestamps();
    }
}

resources/views/comments/_form.blade.php
<div class="mb-2 mt-2">
@auth
<form action="{{ route('posts.comments.store',['post'=>$post->id]) }}" method="POST">
    @csrf
    <div class="form-group">
        <textarea type="text" class="form-control" name="content" ></textarea>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Add Comment</button>
</form>
@error
@enderror
@else
 <a href="{{ route('login') }}">Sign-in</a> to post comments!
@endauth
</div>
<hr/>